"$schema" = 'https://starship.rs/config-schema.json'

format = """
$all\
"""

command_timeout = 1000

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
